openapi: 3.0.0
info:
  title: "Trail Management API"
  description: "API for managing trails"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Trail:
      type: "object"
      required:
        - Trail_Name
      properties:
        TrailID:
          type: "integer"
          description: "Unique identifier for the trail"
        Trail_Name:
          type: "string"
          description: "Name of the trail"
        Trail_Summary:
          type: "string"
          description: "Brief summary of the trail"
        Trail_Description:
          type: "string"
          description: "Detailed description of the trail"
  parameters:
    TrailId:
      name: "TrailID"
      in: path
      description: "ID of the trail"
      required: true
      schema:
        type: "integer"

paths:
  /trails:
    get:
      operationId: "trails.read_all"
      tags:
        - "Trails"
      summary: "Retrieve a list of all trails"
      responses:
        "200":
          description: "List of trails retrieved successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      operationId: "trails.create"
      tags:
        - "Trails"
      summary: "Create a new trail"
      requestBody:
        description: "Trail to create"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
  /trails/{TrailID}:
    get:
      operationId: "trails.read_one"
      tags:
        - "Trails"
      summary: "Retrieve details of a specific trail"
      parameters:
        - $ref: "#/components/parameters/TrailId"
      responses:
        "200":
          description: "Trail details retrieved successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    put:
      operationId: "trails.update"
      tags:
        - "Trails"
      summary: "Update details of a specific trail"
      parameters:
        - $ref: "#/components/parameters/TrailId"
      requestBody:
        description: "Trail data to update"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "200":
          description: "Trail updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    delete:
      operationId: "trails.delete"
      tags:
        - "Trails"
      summary: "Delete a specific trail"
      parameters:
        - $ref: "#/components/parameters/TrailId"
      responses:
        "204":
          description: "Trail deleted successfully"
